version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  celery:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A ecommerce_api worker -l info
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped

  celery-beat:
    build:
      context: .  
      dockerfile: Dockerfile.prod
    command: celery -A ecommerce_api beat -l info
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
    restart: unless-stopped

volumes:
  # No postgres_data anymore
