version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A ecommerce_api worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A ecommerce_api beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  # No need for postgres_data anymore
