apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce-api
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWNoYW5nZS1tZS1pbi1wcm9kdWN0aW9u  # django-insecure-change-me-in-production
  EMAIL_HOST_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==  # your-email-password
  AFRICAS_TALKING_API_KEY: eW91ci1hcGkta2V5  # your-api-key
  AFRICAS_TALKING_SENDER_ID: eW91ci1zZW5kZXItaWQ=  # your-sender-id